package org.example;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import java.util.Random;

public class Main {

        public static void main(String[] args) {
            Random random = new Random();
            int successfulPicks = 0;
            int targetSum = 24;
            int numberOfPicks = 1000000; // Number of simulations

            // Perform the simulation
            for (int i = 0; i < numberOfPicks; i++) {
                int sum = 0;
                boolean[] picked = new boolean[52];
                for (int j = 0; j < 4; j++) {
                    int card;
                    do {
                        card = random.nextInt(52);
                    } while (picked[card]);
                    picked[card] = true;
                    sum += cardValue(card);
                }
                if (sum == targetSum) {
                    successfulPicks++;
                }
            }

            // Display the number of successful picks
            System.out.println("Number of picks that yield the sum of " + targetSum + ": " + successfulPicks);
        }

        // Method to return the card value
        public static int cardValue(int card) {
            int value = card % 13;
            if (value == 0) return 13;  // King
            if (value == 1) return 1;   // Ace
            if (value == 11) return 11; // Jack
            if (value == 12) return 12; // Queen
            return value;
        }
    }


